### ISSUE TITLE
nix-index module does not search in nodePackages

### ISSUE THREAD

**Issue by tobiasBora** [nix-community/nix-index-database#99]
I'm not sure if the issue should be reported here or in `nix-locate`… but I enabled the `nix-index` module, and when I type, the following command, I get:
```
$ pnpm
The program 'pnpm' is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix profile install nixpkgs#corepack_18.out
  nix profile install nixpkgs#corepack.out
  nix profile install nixpkgs#corepack_21.out

Or run it once with:
  nix shell nixpkgs#corepack_18.out -c pnpm ...
  nix shell nixpkgs#corepack.out -c pnpm ...
  nix shell nixpkgs#corepack_21.out -c pnpm ...
```
However, the right package to install here is `nodePackages.pnpm`:
```
$ nix-shell -p nodePackages.pnpm
$ pnpm --version
8.15.13
```
What confuses me even more is that if I type:
```
$ which pnpm
/nix/store/jxyv7qildiy960h194h4ca3wharbbpks-pnpm-8.15.3/bin/pnpm
```
I get a binary in `$out/bin`, but if I search via:
```
$ nix-locate bin/pnpm
nodePackages.pnpm.out                               637 x /nix/store/jxyv7qildiy960h194h4ca3wharbbpks-pnpm-8.15.3/lib/node_modules/.bin/pnpm
nodePackages.pnpm.out                             1,047 x /nix/store/jxyv7qildiy960h194h4ca3wharbbpks-pnpm-8.15.3/lib/node_modules/pnpm/bin/pnpm.cjs
[… other entries unrelated to nodePackages.pnpm …]
```
I only get entries that are in `$out/lib`, while the `$out/bin` does contain the researched binary. I guess this might explain why the `nix-index` module does not propose this package?

**Comment by r-vdp** [comment]
This is because of the way in which `nix-locate` is invoked, the `pnpm` executable in `nodePackages.pnpm` is located at `/nix/store/sfdclih2whss59h76k3slxwf47yv4sah-pnpm-8.15.5/lib/node_modules/.bin/pnpm` and then `lib/node_modules/.bin` gets symlinked to `bin/` in the store path.

`nix-locate` is called with `--at-root --whole-name '/bin/pnpm'` which means it only looks for `bin/pnpm` at the root of store paths and it does not seem to consider the symlink when matching the search pattern (maybe to avoid needing to actively detect cycles?), and so it doesn't find the `pnpm` executable in `nodePackages.pnpm`.

Two ways to improve on this:
1. relax the `--at-root` and  `--whole-name` requirements. This may cause a lot more results to be returned on some queries though, so not sure it's desirable.
2. make `nix-locate` read through symlinks so that it would actually match in this case. This would need to be implemented in nix-index upstream.

In any case, not much we can do in nix-index-database.

**Comment by tobiasBora** [comment]
Thanks for clarifying this, then it seems to be a duplicate of https://github.com/nix-community/nix-index/issues/211
